### ISSUE TITLE
Install / starting on S/4 1909 

### ISSUE THREAD

**Issue by TimoJohn** [DevEpos/abap-tags-backend#3]
Hi @stockbal , thanks you for providing us with your code. 
unfortunately I can't start it on my S/4 1909 Nw 7.54 SP00 system. 

Does it rely on HANA Code search that is to be enables via a business function  ( and eats up lots of space ) ??
I hope that not .... 

I di install your backend via ABAP Git, activated all XSLT manual again but still I face:
<img width="631" alt="image" src="https://user-images.githubusercontent.com/23238730/189640872-44271aca-bd5a-4745-bc23-e6ec49c9aae4.png">

![image](https://user-images.githubusercontent.com/23238730/189641144-b22a3aca-8a33-4d99-8fb7-244c50ce77db.png)

![image](https://user-images.githubusercontent.com/23238730/189641037-30bdfe1e-6881-4ce8-b851-13e0b6509cdf.png)

can you help ne out what is needed else? 
thanks in advance

**Comment by stockbal** [comment]
Hi @TimoJohn,

from your text and your first screen shot I assume you want to run my _ABAP Code Search Plugin_ which needs the abapGit repository [abap-code-search](https://github.com/stockbal/abap-code-search). It does not rely on the HANA Text Search, so it doesn't matter it this function is turned on or not.

To check if everything is installed correctly you should restart eclipse and activate the _ABAP Communication Log_ and activate the logging before you open the eclipse search dialog.

After you open the search dialog, the UI makes the backend request to discover the feature availability. You should see the following marked entry in the log:

![image](https://user-images.githubusercontent.com/35834861/189646169-486aa9ea-409b-43fd-acb4-1d8f4991dcfc.png)

If you still see the error message in the search dialog, it could have something to do with missing authorization's (see [Necessary Authorizations](https://github.com/stockbal/abap-code-search-tools#necessary-authorizations)).

As a side note, please try to always create the issue in the correct repository. For each of my plugins there is a repository for UI part and for the backend part.

I hope these suggestions can resolve your problem.

Best regards,
Ludwig

**Comment by TimoJohn** [comment]
Thank you Ludwig for your fast an kind reply on such a dump question ... 
Incredible that i focused all the time on the wrong BackendPlugin .... somhow I messed up all your plugins I installed today. 

Using the BE you mentioned works like charm!

**Comment by stockbal** [comment]
No problem 🙂.
I hope you enjoy it
